const FormData = [
  {
    Symptoms: [
      {
        id: 1,
        name: "Increase Urination",
        title: "radio",
        cName: "checkBoxLabel",
        category: "symptom",
        options: ["Yes", "No"],
      },
      {
        id: 25,
        name: "Are you feeling drowsy?",
        title: "text",
        cName: "textLabel",
        category: "monitoring",
        options: ["Yes", "No", "May be"],
      },
      {
        id: 2,
        name: "Vision Problems",
        title: "textLabel",
        cName: "checkBoxLabel",
        category: "symptom",
        options: ["Yes", "No"],
      },{
        id: 2,
        name: "Vision Problems",
        title: "textLabel",
        cName: "checkBoxLabel",
        category: "symptom",
        options: ["Yes", "No"],
      },
      {
        id: 3,
        name: "Tingling or Numbness in foot",
        title: "radio",
        cName: "checkBoxLabel",
        category: "symptom",
        options: ["Yes", "No"],
      },
      {
        id: 4,
        name: "Excessive Sweating",
        title: "radio",
        cName: "checkBoxLabel",
        category: "symptom",
        options: ["Yes", "No"],
      },
    ],
  },
  {
    doctors: [
      {
        id: 5,
        name: "Taking medicine regularly Taking medicine regularly Taking medicine regularly",
        title: "radio",
        cName: "textLabel",
        category: "doctorsMedicine",
        options: ["Yes", "No"],
      },
      {
        id: 6,
        name: "Consulted doctor recently",
        title: "radio",
        cName: "textLabel",
        category: "doctorsMedicine",
        options: ["Yes", "No"],
      },
      {
        id: 8,
        name: "Recent hospitalihzation",
        title: "radio",
        cName: "textLabel",
        category: "doctorsMedicine",
        options: ["Yes", "No"],
      },
      {
        id: 9,
        name: "Recent eye check",
        title: "radio",
        cName: "textLabel",
        category: "doctorsMedicine",
        options: ["Yes", "No"],
      },
      {
        id: 10,
        name: "Recent dental check",
        title: "radio",
        cName: "textLabel",
        category: "doctorsMedicine",
        options: ["Yes", "No"],
      },
    ],
  },
  {
    "lab parameters": [
      {
        id: 11,
        name: "Bp Systolic",
        title: "textLabel",
        cName: "textLabel",
        category: "labParameter",
      },
      {
        id: 12,
        name: "Bp HbA1C",
        title: "textLabel",
        cName: "textLabel",
        category: "labParameter",
      },
      {
        id: 13,
        name: "FBS",
        title: "textLabel",
        cName: "textLabel",
        category: "labParameter",
      },
      {
        id: 14,
        name: "PPBS",
        title: "textLabel",
        cName: "textLabel",
        category: "labParameter",
      },
      {
        id: 15,
        name: "TSH",
        title: "textLabel",
        cName: "textLabel",
        category: "labParameter",
      },
      {
        id: 16,
        name: "Prolactin",
        title: "textLabel",
        cName: "textLabel",
        category: "labParameter",
      },
      {
        id: 17,
        name: "BP Diastoic",
        title: "textLabel",
        cName: "textLabel",
        category: "labParameter",
      },
      {
        id: 18,
        name: "Total Cholestrol",
        title: "textLabel",
        cName: "textLabel",
        category: "labParameter",
      },
      {
        id: 19,
        name: "LLDL",
        title: "textLabel",
        cName: "textLabel",
        category: "labParameter",
      },
      {
        id: 20,
        name: "HDL",
        title: "textLabel",
        cName: "textLabel",
        category: "labParameter",
      },
      {
        id: 21,
        name: "VLDL",
        title: "textLabel",
        cName: "textLabel",
        category: "labParameter",
      },
      {
        id: 22,
        name: "ALTH",
        title: "textLabel",
        cName: "textLabel",
        category: "labParameter",
      },
    ],
  },
  {
    monitoring: [
      {
        id: 23,
        name: "Weight",
        title: "textLabel",
        cName: "textLabel",
        category: "monitoring",
      },
      {
        id: 24,
        name: "BloodGlucose",
        title: "textLabel",
        cName: "textLabel",
        category: "monitoring",
      },
    ],
  },
  {
    questions: [
      {
        id: 25,
        name: "Are you feeling drowsy?",
        title: "multiple",
        cName: "textLabel",
        category: "monitoring",
        options: ["Yes", "No", "May be"],
      },
      {
        id: 26,
        name: "Are you hungry?",
        title: "checkbox",
        cName: "textLabel",
        category: "monitoring",
        options: ["Yes", "No", "May be"],
      },
      {
        id: 27,
        name: "Are you happy?",
        title: "checkbox",
        cName: "textLabel",
        category: "monitoring",
        options: ["Yes", "No", "May be", "think"],
      },
    ],
  },
];
export default FormData;
